import type { Module } from "../../types";

export const csrfAttacks: Module = {
  id: "csrf-attacks",
  title: "Cross-Site Request Forgery (CSRF)",
  description:
    "Learn how attackers trick users into performing unwanted actions and how to defend against it.",
  difficulty: "Intermediate",
  xpReward: 350,
  locked: false,
  lessons: [
    {
      id: "csrf-theory",
      title: "Understanding CSRF Attacks",
      type: "theory",
      content: `
# Cross-Site Request Forgery (CSRF)

CSRF is an attack that tricks authenticated users into executing unwanted actions on a web application where they are currently logged in. The attacker forges a request that appears to come from the victim.

## How CSRF Attacks Work

\`\`\`mermaid
sequenceDiagram
    participant User
    participant Attacker Site
    participant Bank

    User->>Bank: 1. Login (get session cookie)
    Bank-->>User: Session established
    User->>Attacker Site: 2. Visit malicious page
    Attacker Site->>Bank: 3. Hidden form submits to bank
    Note right of Bank: Request includes<br/>user's session cookie!
    Bank-->>Attacker Site: 4. Transfer succeeds
    Note over User: User never intended this!
\`\`\`

::video[https://www.youtube.com/watch?v=eWEgUcHPle0]{title="CSRF Attacks Explained" caption="Understanding Cross-Site Request Forgery"}

## Mission Briefing: The Attack Vector

Imagine you are logged into your bank account. An enemy agent sends you an innocent-looking email with a hidden image tag:

\`\`\`html
<img src="https://yourbank.com/transfer?to=attacker&amount=10000" />
\`\`\`

When your browser loads this "image," it sends a real transfer request to the bank—with your valid session cookies attached. The bank cannot distinguish this from a legitimate request.

## Real-World Intel

**Case File #1: TikTok (2020)**
A CSRF vulnerability allowed attackers to change users' account settings and expose private data by tricking users into clicking a malicious link.

**Case File #2: Netflix (2006)**
Attackers could add DVDs to users' rental queues, change shipping addresses, or alter account credentials—all without user consent.

## Why Session Cookies Are Not Enough

Cookies are sent automatically with every request to a domain. The server sees valid authentication but has no way to verify the user *intended* to make that request.

## The Defense: CSRF Tokens

A CSRF token is a unique, unpredictable value generated by the server and embedded in forms. Attackers cannot forge this token because they have no way to read it from another site (thanks to the Same-Origin Policy).
            `,
    },
    {
      id: "csrf-quiz-1",
      title: "CSRF Intelligence Test",
      type: "quiz",
      content: "",
      quiz: {
        question: "What makes CSRF attacks possible?",
        options: [
          "Browsers do not send cookies with cross-origin requests",
          "Browsers automatically include cookies with requests to a domain, regardless of the request's origin",
          "Attackers can read cookies from other websites",
          "Session tokens are stored in localStorage",
        ],
        correctAnswer: 1,
        explanation:
          "Browsers automatically attach cookies to every request to a domain, even if the request originates from a different site. This is what makes CSRF possible—the server receives valid authentication cookies but cannot verify the user's intent.",
      },
    },
    {
      id: "csrf-quiz-2",
      title: "Defense Strategy Assessment",
      type: "quiz",
      content: "",
      quiz: {
        question:
          "Which of the following is the MOST effective defense against CSRF attacks?",
        options: [
          "Using HTTPS for all requests",
          "Validating the Referer header",
          "Implementing synchronizer tokens (CSRF tokens) validated on the server",
          "Setting cookies to HttpOnly",
        ],
        correctAnswer: 2,
        explanation:
          "While other options provide some security benefits, synchronizer tokens (CSRF tokens) are the primary defense. The server generates a unique token per session/request, embeds it in forms, and validates it on submission. Attackers cannot obtain this token due to Same-Origin Policy.",
      },
    },
    {
      id: "csrf-quiz-3",
      title: "Attack Vector Analysis",
      type: "quiz",
      content: "",
      quiz: {
        question:
          "An attacker creates a malicious page with: <form action='https://bank.com/transfer' method='POST'><input type='hidden' name='to' value='attacker'/></form><script>document.forms[0].submit()</script>. What happens if a logged-in bank user visits this page?",
        options: [
          "Nothing—the browser blocks cross-origin form submissions",
          "The form submits but without cookies, so it fails authentication",
          "The form submits with the user's cookies, potentially completing the transfer",
          "The Same-Origin Policy prevents the form from loading",
        ],
        correctAnswer: 2,
        explanation:
          "Cross-origin form submissions ARE allowed by browsers (unlike AJAX requests). The form will submit with the user's cookies attached. Without CSRF protection, the bank's server has no way to distinguish this forged request from a legitimate one.",
      },
    },
    {
      id: "csrf-quiz-4",
      title: "SameSite Cookie Knowledge",
      type: "quiz",
      content: "",
      quiz: {
        question:
          "Modern browsers support the SameSite cookie attribute. What does 'SameSite=Strict' do?",
        options: [
          "Encrypts the cookie value",
          "Prevents the cookie from being sent with any cross-site request",
          "Only allows the cookie on HTTPS connections",
          "Hides the cookie from JavaScript",
        ],
        correctAnswer: 1,
        explanation:
          "SameSite=Strict prevents the browser from sending the cookie with any cross-site request, providing strong CSRF protection. However, it can affect user experience (e.g., clicking a link from email won't include auth cookies). SameSite=Lax is often a better balance.",
      },
    },
    {
      id: "csrf-lab",
      title: "Implement CSRF Protection",
      type: "lab",
      content:
        "The form handler below processes a sensitive action (transferring funds) but has no CSRF protection. Your mission: Add CSRF token validation to prevent forged requests.",
      lab: {
        initialCode: `
function handleTransfer(req, res) {
  // VULNERABLE: No CSRF protection!
  const { to, amount } = req.body;

  // Verify user is authenticated
  if (!req.session.userId) {
    return res.status(401).json({ error: "Not authenticated" });
  }

  // Process the transfer
  const result = transferFunds(req.session.userId, to, amount);

  return res.json({ success: true, result });
}
                `,
        solutionCode: `
function handleTransfer(req, res) {
  const { to, amount, csrfToken } = req.body;

  // Verify user is authenticated
  if (!req.session.userId) {
    return res.status(401).json({ error: "Not authenticated" });
  }

  // SECURE: Validate CSRF token
  if (!csrfToken || csrfToken !== req.session.csrfToken) {
    return res.status(403).json({ error: "Invalid CSRF token" });
  }

  // Process the transfer
  const result = transferFunds(req.session.userId, to, amount);

  return res.json({ success: true, result });
}
                `,
        instructions:
          "Add CSRF token validation: 1) Extract csrfToken from req.body, 2) Compare it against req.session.csrfToken, 3) Return a 403 error with message 'Invalid CSRF token' if validation fails.",
      },
    },
  ],
};
